### PR TITLE
Modifications for successful manage.py migration

### PR DESCRIPTION
**Pull request by mikkeyboi**
The following changes made it possible for me to run the migration.
My python environment is as follows: `conda create -n sql python=3.6 django numpy scipy` and pip installed the dist (with the changes in this PR).

### CODE REVIEW

**Comment by cboulay** [comment]
What is `on_delete=models.PROTECT`?

**Comment by cboulay** [comment]
Where did you see to use `models.DurationField` instead of `models.SubFieldBase`?

**Comment by cboulay** [comment]
i'm pretty sure DurationField is wrong. Take a look at SizedBinaryField (MySQL only) or maybe more simply [`BinaryField`](https://docs.djangoproject.com/en/2.2/ref/models/fields/#binaryfield). I don't know if this is the reason, but it seems that prior to a recent version of Django that BinaryField could not be written to... this might be why I didn't use it. Now it can, so maybe we can use it directly. We still need the from- and to- numpy array wrappers in there.

**Comment by mikkeyboi** [comment]
Okay I'll try BinaryField. Regardless (of where its stored), I'll add `from_db_value()` and `to_python()` wrappers there.
[ForeignKey.on_delete field reference](https://docs.djangoproject.com/en/dev/ref/models/fields/#arguments)
For the `on_delete`, it needed to be defined in ForeignKey as of Django 2.0+ `missing 1 required positional argument: on_delete`. The decision the `PROTECT` argument of the ForeignKey `on_delete` option is because it prevents the referenced object from being deleted if it already has an object referencing it in the database (as compared to `CASCADE`). I think it's a good idea to use `PROTECT` as a safety precaution (ie: In a blog, if there are comments referencing a post it won't let you delete the post until you deal with the comments first. Whereas in cascade, wiping the post will wipe everything that's referenced to it).
Then again, if I wanted to delete a trial I would want everything associated to it to go as well in one sweep. We can decide this on a case-by-case basis.

**Comment by cboulay** [comment]
Please use CASCADE. It’s one of the main desirable features of using a database schema like this.

**Pull request merged**
